
const types = {
    // ADD ITEM
    ADD_ITEMS_START: 'ADD_ITEMS_START',
    ADD_ITEMS_SUCCESS: 'ADD_ITEMS_SUCCESS',
    ADD_ITEMS_FAILURE: 'ADD_ITEMS_FAILURE',

//    DELETE ITEM
    DELETE_ITEM_START: 'DELETE_ITEM_START',
    DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAILURE: 'DELETE_ITEM_FAILURE',

    // ADD ITEM
    ADD_COMMENT_START: 'ADD_COMMENT_START',
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
};

export default types;